// Generated by build_encrypted_guestlist.py — do not edit by hand.
// One XOR-encrypted block per invitation; the key lives only in the
// guest's link fragment (#<id><key>), never here. See POC.md §5.5.
window.GUESTS = {
  v: 1,
  i: 4,
  s: 50000,
  b: {
    "h8tw": "1_myeyqdypl-W6Gbz55rAQXJe61o0Q8yITOqo7zookn4vgFlpAtr4-ptgd19RBO1oEJhQdqPAwP32tLOn2qCkUXwYmpe6Mlqy_yUXZUdXyU9tx2cC-gPVXyxWMZt1H7cbnsrsN7Iz28zYRgbKDrn6Q",
    "aTgA": "IoF5jC07PyivLgGarzfBaQ6WMLKRSeQDWCUGics_mGZUokCFnFchxVmg43ZZTEV8NBVSPy7Qa5oJXhsoOQqSz4vIBn6TLcybEv4F6Qp3pRN4_yPDvlm-NyBJ30ZKM3UN4qEJ2FgqHic5d5gObBIUcw",
    "dBrH": "3Blo_74bajr-7qOmkPWTKrEoUdB4jc94zAaoSmL4Yi1yQCtdkJWKbdSa4cVaxTx3IGAny601DXwcaBuvfjQjvOb0k3BCSHfU5rYihTVH6KJf38bk36D26URS336ISkOiXj7tzlP9XlflMS2PACNsow",
    "HO3x": "yRzNX7-Ii3C1QcgNO0157vn9YGV4L43NY-Ich0gd_X_3rb111aCuBilP27MqzgAwWRQBftyg0Ks9hmusQF3WvBWiOOLpJ2zl2NZsgOwzSqzm-AlI1b1q4a5SGUnnbcYdpSLIr0IJnfxmd1Pjy_pk0w",
    "4cyf": "iUAgvbe7jWOsIdxm9VYpQHKZVTmGL4HQ681FnERbiqsZ-2uc0KMyWUAv5r29y7qO-bi3f_ZRfPh5dC9Ne0esBj3PUdhylrDYjDCFK2mCUZXGICxwEQ30Nx2zOKPUCnHfHmnOFC9FBWgFvViDmB8nng",
    "KDIC": "o09aLPc8qZRh5sLVVR4Uvy0lRqZPG3ShNKqN5iOd6n-sbw9UVJeUxfnSWD64PmVUuZngL9s-kHsdqaZHqVRWk_GwE_IK39UEY-MXHHfaHHm8lKth16_S_lMEDmwmLqoD7h9FtPhK_yJHPh06zLV5gA",
    "hSPI": "Pwzo4lL7TlXsfHsnFOT-dMQ7yJ5xcoxSraQY_He1o8ruGtzZWYq2MxCvkRL3kNT9zBOAjgf2461wv_JDqP_ZTd32s6jXFvKIWZMdmVzp7TajcExU_eINWhms0-teePaOwqJFe-LqD3pcHQFZ9l-G-A",
    "Vq4w": "5Y8kLzp7BObWsnGMBrM6zrd2SCKdZelNF-LkHbaLtgDcm5obnGJ5tVSObqBz6eJ_M4wVgvJULSNPKbmYjOJdDEMIV-QT9-crwJY13H0Z6DorWTUoVEwHAj8Mow8KkDm41pBlXSYwCGTrjpCfVEW28Q",
    "a1ik": "bDCGAnjgdU540oM06XxGarulmbZm9iiPSjEhOzpQtSYQG23nRfGhMdU3WWp3YS8gUnRk1MSXLsBL45Jm5aQIObZuczLgWH-1i6E1qMJzIoaCgDmdfvcZ-nNTwkuEvpuvF7dwkfCTsyzxkG66fCLPTQ",
    "V3uG": "R8EgQdi_krkhG6LqZHEMuF1f-1BqKuY3Qom0pwsSvUGkPv7iy64DT3_EwzeRpleroJPKVCx0aPrRvdeKha6gosRzFM9lGYD1N_dYsOtQTahOA7HzQlm7kV5efuydijgHLp98lURerFuf9AsRBbEY-w",
    "BQ21": "KVYwdFOlH78g0foKZjeu_HKc2xpdqsoGTkBv8fK9T_o5xIUXgEtcclFWDWbFLSQ0KxICf_hOWLsEQKlNgPufRXwsfIHATEK-p9CKyxrDvaxM6v9ek0piYT9C6j0QWtArUK4y7bKzEYc0gRyqYHpLlQ"
  }
};
